apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world # This must match the 'app' label in your Deployment
  ports:
    - protocol: TCP
      port: 80       # Port the service listens on
      targetPort: 80 # Port the container is listening on (NGINX default is 80)
  type: LoadBalancer # This will provision an external load balancer on EKS
